### PR TITLE
No

### PR DESCRIPTION
**Pull request by Jonty**
No

### CODE REVIEW

**Comment by friedkiwi** [comment]
Breaks the build. Resubmit please.

**Comment by marksteward** [comment]
Have you signed the Contributor Licence Agreement?

**Comment by Jonty** [comment]
Tests pass, because there aren't any.

**Comment by marksteward** [comment]
Have you signed the Contributor Licence Agreement?

**Comment by friedkiwi** [comment]
Still doesn't produce any runnable artefacts. Please resubmit.

**Pull request closed without merging**
